# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-30 08:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0003_auto_20160416_1030'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weightentry',
            unique_together=set([]),
        ),
    ]
