# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config', '0003_merge'),
        ('config', '0002_auto_20180503_0228'),
    ]

    operations = [
    ]
