# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 19:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20180503_0228'),
        ('exercises', '0005_merge'),
        ('exercises', '0005_merge'),
        ('exercises', '0004_auto_20180503_1220'),
    ]

    operations = [
    ]
