# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0006_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseimage',
            name='is_main',
            field=models.BooleanField(default=False, help_text='Tick the box if you want to set                                    this image as the main one for the exercise (will                                    be shown e.g. in the search). The first image is                                    automatically marked by the system.', verbose_name='Main picture'),
        ),
    ]
