# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-21 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_merge'),
        ('exercises', '0006_auto_20180511_0740'),
    ]

    operations = [
    ]
