# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-09 13:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='carbohydrates_sugar',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='In g per                                        100g of product', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Sugar content                                            in                                             carbohydrates'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='fat_saturated',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='In g per 100g                                                      of product', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Saturated fat                                                        content in fats'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='license_author',
            field=models.CharField(blank=True, help_text='If you are not the author,                                                    enter the name or source here. This is needed                                                    for some licenses e.g. the CC-BY-SA.', max_length=50, null=True, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='status',
            field=models.CharField(choices=[('1', 'Pending'), ('2', 'Accepted'), ('3', 'Declined'), ('4', 'Submitted by administrator'), ('5', 'System ingredient')], default='1', editable=False, max_length=2),
        ),
        migrations.AlterField(
            model_name='ingredientweightunit',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Unit amount, e.g. "1 Cup" or                                         "1/2 spoon"', max_digits=5, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='order',
            field=models.IntegerField(blank=True, editable=False, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='mealitem',
            name='order',
            field=models.IntegerField(blank=True, editable=False, verbose_name='Order'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='description',
            field=models.TextField(blank=True, help_text='A description of the goal                                                 of the plan, e.g. "Gain mass" or "Prepare                                                  for summer"', max_length=2000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='nutritionplan',
            name='has_goal_calories',
            field=models.BooleanField(default=False, help_text='Tick the box if you                                                          want to mark this plan as having a goal                                                          amount of calories. You can use the                                                          calculator or                                                          enter the value yourself.', verbose_name='Use daily                                                            calories'),
        ),
    ]
