# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 19:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0003_merge'),
        ('nutrition', '0002_auto_20180503_1220'),
    ]

    operations = [
    ]
