# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-21 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nutrition', '0004_mealitem_meal_choice'),
        ('nutrition', '0005_merge'),
    ]

    operations = [
    ]
