# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_auto_20180503_1220'),
        ('gym', '0007_auto_20180507_1839'),
    ]

    operations = [
    ]
