# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-09 13:16
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160303_2340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='full_name',
            field=models.CharField(help_text='If a license has been localized, e.g.                                 the Creative Commons licenses for the different                                 countries, add them as separate entries here.', max_length=60, verbose_name='Full name'),
        ),
        migrations.AlterField(
            model_name='license',
            name='short_name',
            field=models.CharField(max_length=15, verbose_name='Short name,                                                 e.g. CC-BY-SA 3'),
        ),
        migrations.AlterField(
            model_name='license',
            name='url',
            field=models.URLField(blank=True, help_text='Link to license text                                       or other information', null=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='calories',
            field=models.IntegerField(default=2500, help_text='Total caloric intake,                                         including e.g. any surplus', null=True, validators=[django.core.validators.MinValueValidator(1500), django.core.validators.MaxValueValidator(5000)], verbose_name='Total daily calories'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='ro_access',
            field=models.BooleanField(default=False, help_text='Allow external users to access                                   your workouts and logs in a read-only mode.                                    You need to set this before you can share links e.g.                                    to social media.', verbose_name='Allow external access'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='sleep_hours',
            field=models.IntegerField(default=7, help_text='The average hours                                             of sleep per day', null=True, validators=[django.core.validators.MinValueValidator(4), django.core.validators.MaxValueValidator(10)], verbose_name='Hours of sleep'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='timer_pause',
            field=models.IntegerField(default=90, help_text='Default duration in seconds                                             of pauses used by the timer in the gym mode.', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(400)], verbose_name='Default duration of                                               workout pauses'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workout_duration',
            field=models.IntegerField(default=12, help_text='Default duration in                                                 weeks of workouts not in a schedule. Used                                                 for email workout reminders.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Default duration                                                     of workouts'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workout_reminder',
            field=models.IntegerField(default=14, help_text='The number of days you want                                                 to be reminded before a workout expires.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Remind before expiration'),
        ),
    ]
