# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180507_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='add_user_rest_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='created_by_api',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
