# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20180510_1910'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='created_by_api',
            new_name='created_by',
        ),
    ]
