# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-11 01:21

from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_merge'),
        ('core', '0012_auto_20180510_2042'),
    ]

    operations = [
    ]
