# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-11 12:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_merge'),
        ('core', '0013_auto_20180511_0146'),
    ]

    operations = [
    ]
