# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_auto_20180508_0144'),
        ('manager', '0010_merge'),
    ]

    operations = [
    ]
