# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-10 22:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_auto_20180430_1302'),
        ('manager', '0011_merge'),
    ]

    operations = [
    ]
