# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='workout_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='manager.WorkoutLog', verbose_name='Workout log'),
        ),
    ]
