# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2018-05-28 15:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0013_workoutsession_workout_log'),
        ('manager', '0013_auto_20180521_1123'),
    ]

    operations = [
    ]
